version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: logs
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data



# Apos instalar a imagem, garantir a ativação do timescaledb.
# CREATE EXTENSION IF NOT EXISTS timescaledb;